#!/bin/bash

# sample script
next line
next line
next line
next line
next line
next line
another line
next line
another line
next line
next line
next line
next line
next line
next line
next line
next line
next line
next line
next line
next line
next line
next line
next line
next line from test1
next line
next line
next line
