#!/bin/bash

# sample script
next line
next line
next line
next line
next line
next line
another line
next line
another line
next line
next line
next line
next line
next line
next line
next line
next line
next line
next line
next line
next line
next line
next line
